/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as WorkspaceRouteRouteImport } from './routes/_workspace/route'
import { Route as WorkspaceIndexRouteImport } from './routes/_workspace/index'
import { Route as ProposalPublicTokenRouteImport } from './routes/proposal/$publicToken'
import { Route as DocumentsPrintRouteImport } from './routes/documents/print'
import { Route as WorkspaceApprovalsRouteImport } from './routes/_workspace/approvals'
import { Route as WorkspaceSettingsRouteRouteImport } from './routes/_workspace/settings/route'
import { Route as AuthSignInIndexRouteImport } from './routes/auth/sign-in/index'
import { Route as AuthOnboardingIndexRouteImport } from './routes/auth/onboarding/index'
import { Route as WorkspaceSettingsIndexRouteImport } from './routes/_workspace/settings/index'
import { Route as WorkspaceProposalsIndexRouteImport } from './routes/_workspace/proposals/index'
import { Route as WorkspaceInvoicesIndexRouteImport } from './routes/_workspace/invoices/index'
import { Route as WorkspaceIntegrationsIndexRouteImport } from './routes/_workspace/integrations/index'
import { Route as WorkspaceClientsIndexRouteImport } from './routes/_workspace/clients/index'
import { Route as InternalEmailRenderRouteImport } from './routes/internal/email/render'
import { Route as AuthInviteAcceptRouteImport } from './routes/auth/invite/accept'
import { Route as WorkspaceSettingsTabRouteImport } from './routes/_workspace/settings/$tab'
import { Route as WorkspaceProposalsProposalIdRouteImport } from './routes/_workspace/proposals/$proposalId'
import { Route as WorkspaceInvoicesInvoiceIdRouteImport } from './routes/_workspace/invoices/$invoiceId'
import { Route as WorkspaceClientsDealsRouteImport } from './routes/_workspace/clients/deals'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRouteRoute = WorkspaceRouteRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIndexRoute = WorkspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const ProposalPublicTokenRoute = ProposalPublicTokenRouteImport.update({
  id: '/proposal/$publicToken',
  path: '/proposal/$publicToken',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsPrintRoute = DocumentsPrintRouteImport.update({
  id: '/documents/print',
  path: '/documents/print',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceApprovalsRoute = WorkspaceApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceSettingsRouteRoute = WorkspaceSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const AuthSignInIndexRoute = AuthSignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthOnboardingIndexRoute = AuthOnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const WorkspaceSettingsIndexRoute = WorkspaceSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceSettingsRouteRoute,
} as any)
const WorkspaceProposalsIndexRoute = WorkspaceProposalsIndexRouteImport.update({
  id: '/proposals/',
  path: '/proposals/',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceInvoicesIndexRoute = WorkspaceInvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceIntegrationsIndexRoute =
  WorkspaceIntegrationsIndexRouteImport.update({
    id: '/integrations/',
    path: '/integrations/',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceClientsIndexRoute = WorkspaceClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const InternalEmailRenderRoute = InternalEmailRenderRouteImport.update({
  id: '/internal/email/render',
  path: '/internal/email/render',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthInviteAcceptRoute = AuthInviteAcceptRouteImport.update({
  id: '/invite/accept',
  path: '/invite/accept',
  getParentRoute: () => AuthRouteRoute,
} as any)
const WorkspaceSettingsTabRoute = WorkspaceSettingsTabRouteImport.update({
  id: '/$tab',
  path: '/$tab',
  getParentRoute: () => WorkspaceSettingsRouteRoute,
} as any)
const WorkspaceProposalsProposalIdRoute =
  WorkspaceProposalsProposalIdRouteImport.update({
    id: '/proposals/$proposalId',
    path: '/proposals/$proposalId',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceInvoicesInvoiceIdRoute =
  WorkspaceInvoicesInvoiceIdRouteImport.update({
    id: '/invoices/$invoiceId',
    path: '/invoices/$invoiceId',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)
const WorkspaceClientsDealsRoute = WorkspaceClientsDealsRouteImport.update({
  id: '/clients/deals',
  path: '/clients/deals',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof WorkspaceIndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/settings': typeof WorkspaceSettingsRouteRouteWithChildren
  '/approvals': typeof WorkspaceApprovalsRoute
  '/documents/print': typeof DocumentsPrintRoute
  '/proposal/$publicToken': typeof ProposalPublicTokenRoute
  '/clients/deals': typeof WorkspaceClientsDealsRoute
  '/invoices/$invoiceId': typeof WorkspaceInvoicesInvoiceIdRoute
  '/proposals/$proposalId': typeof WorkspaceProposalsProposalIdRoute
  '/settings/$tab': typeof WorkspaceSettingsTabRoute
  '/auth/invite/accept': typeof AuthInviteAcceptRoute
  '/internal/email/render': typeof InternalEmailRenderRoute
  '/clients/': typeof WorkspaceClientsIndexRoute
  '/integrations/': typeof WorkspaceIntegrationsIndexRoute
  '/invoices/': typeof WorkspaceInvoicesIndexRoute
  '/proposals/': typeof WorkspaceProposalsIndexRoute
  '/settings/': typeof WorkspaceSettingsIndexRoute
  '/auth/onboarding/': typeof AuthOnboardingIndexRoute
  '/auth/sign-in/': typeof AuthSignInIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/approvals': typeof WorkspaceApprovalsRoute
  '/documents/print': typeof DocumentsPrintRoute
  '/proposal/$publicToken': typeof ProposalPublicTokenRoute
  '/': typeof WorkspaceIndexRoute
  '/clients/deals': typeof WorkspaceClientsDealsRoute
  '/invoices/$invoiceId': typeof WorkspaceInvoicesInvoiceIdRoute
  '/proposals/$proposalId': typeof WorkspaceProposalsProposalIdRoute
  '/settings/$tab': typeof WorkspaceSettingsTabRoute
  '/auth/invite/accept': typeof AuthInviteAcceptRoute
  '/internal/email/render': typeof InternalEmailRenderRoute
  '/clients': typeof WorkspaceClientsIndexRoute
  '/integrations': typeof WorkspaceIntegrationsIndexRoute
  '/invoices': typeof WorkspaceInvoicesIndexRoute
  '/proposals': typeof WorkspaceProposalsIndexRoute
  '/settings': typeof WorkspaceSettingsIndexRoute
  '/auth/onboarding': typeof AuthOnboardingIndexRoute
  '/auth/sign-in': typeof AuthSignInIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_workspace': typeof WorkspaceRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/_workspace/settings': typeof WorkspaceSettingsRouteRouteWithChildren
  '/_workspace/approvals': typeof WorkspaceApprovalsRoute
  '/documents/print': typeof DocumentsPrintRoute
  '/proposal/$publicToken': typeof ProposalPublicTokenRoute
  '/_workspace/': typeof WorkspaceIndexRoute
  '/_workspace/clients/deals': typeof WorkspaceClientsDealsRoute
  '/_workspace/invoices/$invoiceId': typeof WorkspaceInvoicesInvoiceIdRoute
  '/_workspace/proposals/$proposalId': typeof WorkspaceProposalsProposalIdRoute
  '/_workspace/settings/$tab': typeof WorkspaceSettingsTabRoute
  '/auth/invite/accept': typeof AuthInviteAcceptRoute
  '/internal/email/render': typeof InternalEmailRenderRoute
  '/_workspace/clients/': typeof WorkspaceClientsIndexRoute
  '/_workspace/integrations/': typeof WorkspaceIntegrationsIndexRoute
  '/_workspace/invoices/': typeof WorkspaceInvoicesIndexRoute
  '/_workspace/proposals/': typeof WorkspaceProposalsIndexRoute
  '/_workspace/settings/': typeof WorkspaceSettingsIndexRoute
  '/auth/onboarding/': typeof AuthOnboardingIndexRoute
  '/auth/sign-in/': typeof AuthSignInIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/$'
    | '/settings'
    | '/approvals'
    | '/documents/print'
    | '/proposal/$publicToken'
    | '/clients/deals'
    | '/invoices/$invoiceId'
    | '/proposals/$proposalId'
    | '/settings/$tab'
    | '/auth/invite/accept'
    | '/internal/email/render'
    | '/clients/'
    | '/integrations/'
    | '/invoices/'
    | '/proposals/'
    | '/settings/'
    | '/auth/onboarding/'
    | '/auth/sign-in/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/$'
    | '/approvals'
    | '/documents/print'
    | '/proposal/$publicToken'
    | '/'
    | '/clients/deals'
    | '/invoices/$invoiceId'
    | '/proposals/$proposalId'
    | '/settings/$tab'
    | '/auth/invite/accept'
    | '/internal/email/render'
    | '/clients'
    | '/integrations'
    | '/invoices'
    | '/proposals'
    | '/settings'
    | '/auth/onboarding'
    | '/auth/sign-in'
  id:
    | '__root__'
    | '/_workspace'
    | '/auth'
    | '/$'
    | '/_workspace/settings'
    | '/_workspace/approvals'
    | '/documents/print'
    | '/proposal/$publicToken'
    | '/_workspace/'
    | '/_workspace/clients/deals'
    | '/_workspace/invoices/$invoiceId'
    | '/_workspace/proposals/$proposalId'
    | '/_workspace/settings/$tab'
    | '/auth/invite/accept'
    | '/internal/email/render'
    | '/_workspace/clients/'
    | '/_workspace/integrations/'
    | '/_workspace/invoices/'
    | '/_workspace/proposals/'
    | '/_workspace/settings/'
    | '/auth/onboarding/'
    | '/auth/sign-in/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  WorkspaceRouteRoute: typeof WorkspaceRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  DocumentsPrintRoute: typeof DocumentsPrintRoute
  ProposalPublicTokenRoute: typeof ProposalPublicTokenRoute
  InternalEmailRenderRoute: typeof InternalEmailRenderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace': {
      id: '/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/': {
      id: '/_workspace/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/proposal/$publicToken': {
      id: '/proposal/$publicToken'
      path: '/proposal/$publicToken'
      fullPath: '/proposal/$publicToken'
      preLoaderRoute: typeof ProposalPublicTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/print': {
      id: '/documents/print'
      path: '/documents/print'
      fullPath: '/documents/print'
      preLoaderRoute: typeof DocumentsPrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/approvals': {
      id: '/_workspace/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof WorkspaceApprovalsRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/settings': {
      id: '/_workspace/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof WorkspaceSettingsRouteRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/auth/sign-in/': {
      id: '/auth/sign-in/'
      path: '/sign-in'
      fullPath: '/auth/sign-in/'
      preLoaderRoute: typeof AuthSignInIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/onboarding/': {
      id: '/auth/onboarding/'
      path: '/onboarding'
      fullPath: '/auth/onboarding/'
      preLoaderRoute: typeof AuthOnboardingIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_workspace/settings/': {
      id: '/_workspace/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof WorkspaceSettingsIndexRouteImport
      parentRoute: typeof WorkspaceSettingsRouteRoute
    }
    '/_workspace/proposals/': {
      id: '/_workspace/proposals/'
      path: '/proposals'
      fullPath: '/proposals/'
      preLoaderRoute: typeof WorkspaceProposalsIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/invoices/': {
      id: '/_workspace/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof WorkspaceInvoicesIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/integrations/': {
      id: '/_workspace/integrations/'
      path: '/integrations'
      fullPath: '/integrations/'
      preLoaderRoute: typeof WorkspaceIntegrationsIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/clients/': {
      id: '/_workspace/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof WorkspaceClientsIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/internal/email/render': {
      id: '/internal/email/render'
      path: '/internal/email/render'
      fullPath: '/internal/email/render'
      preLoaderRoute: typeof InternalEmailRenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/invite/accept': {
      id: '/auth/invite/accept'
      path: '/invite/accept'
      fullPath: '/auth/invite/accept'
      preLoaderRoute: typeof AuthInviteAcceptRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_workspace/settings/$tab': {
      id: '/_workspace/settings/$tab'
      path: '/$tab'
      fullPath: '/settings/$tab'
      preLoaderRoute: typeof WorkspaceSettingsTabRouteImport
      parentRoute: typeof WorkspaceSettingsRouteRoute
    }
    '/_workspace/proposals/$proposalId': {
      id: '/_workspace/proposals/$proposalId'
      path: '/proposals/$proposalId'
      fullPath: '/proposals/$proposalId'
      preLoaderRoute: typeof WorkspaceProposalsProposalIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/invoices/$invoiceId': {
      id: '/_workspace/invoices/$invoiceId'
      path: '/invoices/$invoiceId'
      fullPath: '/invoices/$invoiceId'
      preLoaderRoute: typeof WorkspaceInvoicesInvoiceIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/_workspace/clients/deals': {
      id: '/_workspace/clients/deals'
      path: '/clients/deals'
      fullPath: '/clients/deals'
      preLoaderRoute: typeof WorkspaceClientsDealsRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
  }
}

interface WorkspaceSettingsRouteRouteChildren {
  WorkspaceSettingsTabRoute: typeof WorkspaceSettingsTabRoute
  WorkspaceSettingsIndexRoute: typeof WorkspaceSettingsIndexRoute
}

const WorkspaceSettingsRouteRouteChildren: WorkspaceSettingsRouteRouteChildren =
  {
    WorkspaceSettingsTabRoute: WorkspaceSettingsTabRoute,
    WorkspaceSettingsIndexRoute: WorkspaceSettingsIndexRoute,
  }

const WorkspaceSettingsRouteRouteWithChildren =
  WorkspaceSettingsRouteRoute._addFileChildren(
    WorkspaceSettingsRouteRouteChildren,
  )

interface WorkspaceRouteRouteChildren {
  WorkspaceSettingsRouteRoute: typeof WorkspaceSettingsRouteRouteWithChildren
  WorkspaceApprovalsRoute: typeof WorkspaceApprovalsRoute
  WorkspaceIndexRoute: typeof WorkspaceIndexRoute
  WorkspaceClientsDealsRoute: typeof WorkspaceClientsDealsRoute
  WorkspaceInvoicesInvoiceIdRoute: typeof WorkspaceInvoicesInvoiceIdRoute
  WorkspaceProposalsProposalIdRoute: typeof WorkspaceProposalsProposalIdRoute
  WorkspaceClientsIndexRoute: typeof WorkspaceClientsIndexRoute
  WorkspaceIntegrationsIndexRoute: typeof WorkspaceIntegrationsIndexRoute
  WorkspaceInvoicesIndexRoute: typeof WorkspaceInvoicesIndexRoute
  WorkspaceProposalsIndexRoute: typeof WorkspaceProposalsIndexRoute
}

const WorkspaceRouteRouteChildren: WorkspaceRouteRouteChildren = {
  WorkspaceSettingsRouteRoute: WorkspaceSettingsRouteRouteWithChildren,
  WorkspaceApprovalsRoute: WorkspaceApprovalsRoute,
  WorkspaceIndexRoute: WorkspaceIndexRoute,
  WorkspaceClientsDealsRoute: WorkspaceClientsDealsRoute,
  WorkspaceInvoicesInvoiceIdRoute: WorkspaceInvoicesInvoiceIdRoute,
  WorkspaceProposalsProposalIdRoute: WorkspaceProposalsProposalIdRoute,
  WorkspaceClientsIndexRoute: WorkspaceClientsIndexRoute,
  WorkspaceIntegrationsIndexRoute: WorkspaceIntegrationsIndexRoute,
  WorkspaceInvoicesIndexRoute: WorkspaceInvoicesIndexRoute,
  WorkspaceProposalsIndexRoute: WorkspaceProposalsIndexRoute,
}

const WorkspaceRouteRouteWithChildren = WorkspaceRouteRoute._addFileChildren(
  WorkspaceRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthInviteAcceptRoute: typeof AuthInviteAcceptRoute
  AuthOnboardingIndexRoute: typeof AuthOnboardingIndexRoute
  AuthSignInIndexRoute: typeof AuthSignInIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthInviteAcceptRoute: AuthInviteAcceptRoute,
  AuthOnboardingIndexRoute: AuthOnboardingIndexRoute,
  AuthSignInIndexRoute: AuthSignInIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  WorkspaceRouteRoute: WorkspaceRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  DocumentsPrintRoute: DocumentsPrintRoute,
  ProposalPublicTokenRoute: ProposalPublicTokenRoute,
  InternalEmailRenderRoute: InternalEmailRenderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
